In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Shaurya Tiwari\Desktop\Machine Learning\ML project-18\covtype.csv")

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df.head()

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0       2596      51      3                               258   
1       2590      56      2                               212   
2       2804     139      9                               268   
3       2785     155     18                               242   
4       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0            221             232            148   
1            220             235            151   
2            234             238            135   
3            238             238            122   
4            220             234            150   

   Horizontal_Distance_To_Fire_Points  Wilderness_Area1  Wilderness_Area2  \
0                                6279                 1                 0   
1                                6225                 1                 0   
2                                6121                 1                 0   
3                                6211                 1                 0   
4                                6172                 1                 0   

   Wilderness_Area3  Wilderness_Area4  Soil_Type1  Soil_Type2  Soil_Type3  \
0                 0                 0           0           0           0   
1                 0                 0           0           0           0   
2                 0                 0           0           0           0   
3                 0                 0           0           0           0   
4                 0                 0           0           0           0   

   Soil_Type4  Soil_Type5  Soil_Type6  Soil_Type7  Soil_Type8  Soil_Type9  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   Soil_Type10  Soil_Type11  Soil_Type12  Soil_Type13  Soil_Type14  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            1            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type15  Soil_Type16  Soil_Type17  Soil_Type18  Soil_Type19  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type20  Soil_Type21  Soil_Type22  Soil_Type23  Soil_Type24  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type25  Soil_Type26  Soil_Type27  Soil_Type28  Soil_Type29  \
0            0            0            0            0            1   
1            0            0            0            0            1   
2            0        

In [6]:
def get_df_info(df):
    print("\n\033[1mShape of DataFrame:\033[0m ", df.shape)
    print("\n\033[1mColumns in DataFrame:\033[0m ", df.columns.to_list())
    print("\n\033[1mData types of columns:\033[0m\n", df.dtypes)
    print("\n\033[1mInformation about DataFrame:\033[0m")
    df.info()
    print("\n\033[1mNumber of unique values in each column:\033[0m")
    for col in df.columns:
        print(f"\033[1m{col}\033[0m: {df[col].nunique()}")
        print("\n\033[1mNumber of null values in each column:\033[0m\n", df.isnull().sum())
        print("\n\033[1mNumber of duplicate rows:\033[0m ", df.duplicated().sum())
        print("\n\033[1mDescriptive statistics of DataFrame:\033[0m\n", df.describe().transpose())

get_df_info(df)
        
        
        
    


Shape of DataFrame:  (581012, 55)

Columns in DataFrame:  ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1', 'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4', 'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5', 'Soil_Type6', 'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10', 'Soil_Type11', 'Soil_Type12', 'Soil_Type13', 'Soil_Type14', 'Soil_Type15', 'Soil_Type16', 'Soil_Type17', 'Soil_Type18', 'Soil_Type19', 'Soil_Type20', 'Soil_Type21', 'Soil_Type22', 'Soil_Type23', 'Soil_Type24', 'Soil_Type25', 'Soil_Type26', 'Soil_Type27', 'Soil_Type28', 'Soil_Type29', 'Soil_Type30', 'Soil_Type31', 'Soil_Type32', 'Soil_Type33', 'Soil_Type34', 'Soil_Type35', 'Soil_Type36', 'Soil_Type37', 'Soil_Type38', 'Soil_Type39', 'Soil_Type40', 'Cover_Type']

Data types of columns:
 Ele

In [8]:
#Splitting X and y
X = df.drop('Cover_Type',axis=1)
y = df['Cover_Type']

### Train_Test_Split

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=101)

### Logistic Regression

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [11]:
lg = LogisticRegression()
lg.fit(X_train, y_train)
y_pred_lg = lg.predict(X_test)

C:\Users\Shaurya Tiwari\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
accuracy_score(y_test, y_pred_lg)

0.6190029517310225

In [13]:
print(classification_report(y_test, y_pred_lg))

C:\Users\Shaurya Tiwari\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           1       0.61      0.64      0.62     42016
           2       0.63      0.77      0.69     56815
           3       0.60      0.22      0.32      7227
           4       0.00      0.00      0.00       563
           5       0.00      0.00      0.00      1896
           6       0.21      0.01      0.01      3505
           7       0.00      0.00      0.00      4181

    accuracy                           0.62    116203
   macro avg       0.29      0.23      0.24    116203
weighted avg       0.57      0.62      0.58    116203



C:\Users\Shaurya Tiwari\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Shaurya Tiwari\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
confusion_matrix(y_test, y_pred_lg)

array([[26811, 15085,    94,     0,     0,     3,    23],
       [12841, 43490,   467,     0,     0,    16,     1],
       [  143,  5408,  1606,     0,     0,    70,     0],
       [    0,   481,    82,     0,     0,     0,     0],
       [  205,  1681,    10,     0,     0,     0,     0],
       [  189,  2854,   439,     0,     0,    23,     0],
       [ 3700,   481,     0,     0,     0,     0,     0]], dtype=int64)

### Decision-Tree

In [15]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

In [16]:
accuracy_score(y_test, y_pred_dt)

0.939683140710653

In [17]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           1       0.94      0.94      0.94     42016
           2       0.95      0.95      0.95     56815
           3       0.93      0.93      0.93      7227
           4       0.85      0.81      0.83       563
           5       0.84      0.82      0.83      1896
           6       0.88      0.88      0.88      3505
           7       0.94      0.95      0.95      4181

    accuracy                           0.94    116203
   macro avg       0.91      0.90      0.90    116203
weighted avg       0.94      0.94      0.94    116203



In [19]:
confusion_matrix(y_test, y_pred_dt)

array([[39398,  2363,     3,     0,    39,     8,   205],
       [ 2301, 53997,   152,     2,   238,    94,    31],
       [    1,   152,  6738,    63,    15,   258,     0],
       [    0,     0,    74,   458,     0,    31,     0],
       [   34,   277,    16,     0,  1557,    11,     1],
       [    5,   105,   290,    14,     4,  3087,     0],
       [  197,    25,     0,     0,     0,     0,  3959]], dtype=int64)

### Random Forest

In [20]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
y_pred_rfc = rfc.predict(X_test)

In [21]:
accuracy_score(y_test, y_pred_rfc)

0.9547343872361299

In [23]:
print(classification_report(y_test, y_pred_rfc))

              precision    recall  f1-score   support

           1       0.96      0.94      0.95     42016
           2       0.95      0.97      0.96     56815
           3       0.94      0.96      0.95      7227
           4       0.93      0.85      0.89       563
           5       0.93      0.76      0.84      1896
           6       0.93      0.90      0.91      3505
           7       0.98      0.95      0.96      4181

    accuracy                           0.95    116203
   macro avg       0.95      0.91      0.93    116203
weighted avg       0.95      0.95      0.95    116203



In [25]:
confusion_matrix(y_test,y_pred_rfc)

array([[39654,  2257,     3,     0,    11,     7,    84],
       [ 1272, 55271,   114,     3,    83,    61,    11],
       [    0,    98,  6971,    25,     6,   127,     0],
       [    0,     0,    57,   480,     0,    26,     0],
       [   23,   400,    20,     0,  1450,     3,     0],
       [    3,   112,   239,    10,     2,  3139,     0],
       [  177,    26,     0,     0,     0,     0,  3978]], dtype=int64)

### Extra Trees

In [30]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier()
etc.fit(X_train, y_train)
y_pred_etc = etc.predict(X_test)

In [32]:
accuracy_score(y_test, y_pred_etc)

0.9538566129962222

In [33]:
print(classification_report(y_test, y_pred_etc))

              precision    recall  f1-score   support

           1       0.96      0.94      0.95     42016
           2       0.95      0.97      0.96     56815
           3       0.94      0.97      0.95      7227
           4       0.93      0.84      0.88       563
           5       0.93      0.79      0.85      1896
           6       0.93      0.90      0.92      3505
           7       0.97      0.96      0.97      4181

    accuracy                           0.95    116203
   macro avg       0.95      0.91      0.93    116203
weighted avg       0.95      0.95      0.95    116203



In [34]:
confusion_matrix(y_test, y_pred_etc)

array([[39567,  2334,     5,     0,    12,     6,    92],
       [ 1367, 55152,   121,     2,    94,    67,    12],
       [    0,    78,  6992,    27,     9,   121,     0],
       [    0,     0,    63,   471,     0,    29,     0],
       [   29,   354,    14,     0,  1493,     6,     0],
       [    4,   104,   223,     8,     3,  3163,     0],
       [  153,    24,     0,     0,     1,     0,  4003]], dtype=int64)